# Site settings
theme: jekyll-theme-minimal
logo: /images/zane.jpg
title: Zane's blog
SEOTitle: Zane的博客 | Zane Blog
email: zane.wang@jahport.com
keyword: "zane"
url: "https://wz472766136.github.io"
baseurl: ""
show_downloads: true
google_analytics:

